name: json_dart
description: The well-tested helpers for convenient work with JSON types.
repository: https://github.com/signmotion/json_dart

topics:
  - json
  - extension
  - converter
  - serialize
  - stringify

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
